/* import localFont from "next/font/local"

export const inter = localFont({
    src:[
        {
            path:"../../public/fonts/InterExtraLight.otf",
            weight:"200",
            style:"normal"
        },
        {
            path:"../../public/fonts/InterLight.otf",
            weight:"300",
            style:"normal"
        },
        {
            path:"../../public/fonts/InterRegular.otf",
            weight:"400",
            style:"normal"
        },
        {
            path:"../../public/fonts/InterMedium.otf",
            weight:"500",
            style:"normal"
        },
        {
            path:"../../public/fonts/InterSemiBold.otf",
            weight:"600",
            style:"normal"
        },
        {
            path:"../../public/fonts/Bold.otf",
            weight:"700",
            style:"normal"
        },
        {
            path:"../../public/fonts/ExtraBold.otf",
            weight:"800",
            style:"normal"
        },
        {
            path:"../../public/fonts/Heavy.otf",
            weight:"900",
            style:"normal"
        },
        {
            path:"../../public/fonts/InterBlack.otf",
            weight:"600",
            style:"italic"
        },
        {
            path:"../../public/fonts/InterBoldItalic.otf",
            weight:"700",
            style:"italic"
        },
        {
            path:"../../public/fonts/InterBlackItalic.otf",
            weight:"900",
            style:"italic"
        },
    ]
}) */